# Generated by Django 4.2.18 on 2025-01-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chefs/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
