# Generated by Django 4.2.18 on 2025-02-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_chefprofile_delete_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='photo_large',
            field=models.ImageField(blank=True, null=True, upload_to='chefs/large/'),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='photo_small',
            field=models.ImageField(blank=True, null=True, upload_to='chefs/small/'),
        ),
    ]
