# Generated by Django 4.2.18 on 2025-05-20 21:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0004_remove_chefprofile_photo_chefprofile_photo_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='photo_small',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_small'),
        ),
    ]
