# Generated by Django 4.2.18 on 2025-05-20 22:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0005_alter_chefprofile_photo_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='photo_large',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_large'),
        ),
    ]
