# Generated by Django 4.2.18 on 2025-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_comment_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='challenge',
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
    ]
