# Generated by Django 4.2.18 on 2025-01-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_difficulty_alter_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default='30 min', help_text='Cooking time in minutes', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default='30 min', help_text='Preparation time in minutes', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default='4 Personne', help_text='Number of servings', max_length=15),
            preserve_default=False,
        ),
    ]
