# Generated by Django 4.2.18 on 2025-01-31 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_chefprofile_delete_chef'),
        ('recipes', '0007_recipe_cook_time_recipe_prep_time_recipe_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_recipes', to='chefs.chefprofile'),
            preserve_default=False,
        ),
    ]
