# Generated by Django 4.2.18 on 2025-02-03 19:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_average_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
